// [_this] call orbis_atc_fnc_addATCConsole;
// [_this] call orbis_atc_fnc_addRadarScreen;

orbis_atc_fnc_addACEInteractMenu = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_addACEInteractMenu.sqf";
orbis_atc_fnc_addATCConsole = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_addATCConsole.sqf";
orbis_atc_fnc_addRadarScreen = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_addRadarScreen.sqf";
orbis_atc_fnc_atcRadarExit = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_atcRadarExit.sqf";
orbis_atc_fnc_atcRadarLoop = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_atcRadarLoop.sqf";
orbis_atc_fnc_createMarkers = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_createMarkers.sqf";
orbis_atc_fnc_createTrails = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_createTrails.sqf";
orbis_atc_fnc_eachFrameHandler = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_eachFrameHandler.sqf";
orbis_atc_fnc_getAutoTransponders = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_getAutoTransponders.sqf";
orbis_atc_fnc_getInAddAction = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_getInAddAction.sqf";
orbis_atc_fnc_listenATISbroadcast = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_listenATISbroadcast.sqf";
orbis_atc_fnc_periodicCheck = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_periodicCheck.sqf";
orbis_atc_fnc_playAndSleep = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_playAndSleep.sqf";
orbis_atc_fnc_radarScreenOff = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_radarScreenOff.sqf";
orbis_atc_fnc_radarScreenOn = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_radarScreenOn.sqf";
orbis_atc_fnc_speakATIS = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_speakATIS.sqf";
orbis_atc_fnc_speakNumber = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_speakNumber.sqf";
orbis_atc_fnc_updateATISdata = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_updateATISdata.sqf";
orbis_atc_fnc_updateMarkerSpacing = compile preProcessFileLineNumbers "orbis_atc_environment\scripts\fnc_updateMarkerSpacing.sqf";
