orbis_ground_fnc_attachTowingVehicle = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_attachTowingVehicle.sqf";
orbis_ground_fnc_canAttachTowingVehicle = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_canAttachTowingVehicle.sqf";
orbis_ground_fnc_deployTowBar = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_deployTowBar.sqf";
orbis_ground_fnc_parkingBrakeRelease = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_parkingBrakeRelease.sqf";
orbis_ground_fnc_parkingBrakeSet = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_parkingBrakeSet.sqf";
orbis_ground_fnc_removeTowBar = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_removeTowBar.sqf";
