orbis_aerodynamics_fnc_fixedWingInit = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_fixedWingInit.sqf";
orbis_aerodynamics_fnc_fixedWingLoop = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_fixedWingLoop.sqf";
orbis_aerodynamics_fnc_getAeroConfig = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_getAeroConfig.sqf";
orbis_aerodynamics_fnc_getDrag = compile preProcessFileLineNumbers "orbis_aerodynamics\scripts\fnc_getDrag.sqf";
