#include "script_component.hpp"

params ["_unit", "_position", "_vehicle", "_turret"];

private _hasAction = _vehicle getVariable [QGVAR(hasAction), false];
if (_hasAction || !(_vehicle isKindOf "Plane")) exitWith {};

_vehicle addAction ["Turn off GPWS", "(_this select 0) setVariable ['GVAR(GPWSmode)', 'off', true]", nil, 1.0111, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] != 'off')", 100];
_vehicle addAction ["Set to B747 GPWS", "(_this select 0) setVariable ['GVAR(GPWSmode)', 'b747', true]", nil, 1.01121, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] != 'b747')", 100];
_vehicle addAction ["Set to Betty (F-16)", "(_this select 0) setVariable ['GVAR(GPWSmode)', 'f16', true]", nil, 1.01122, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] != 'f16')", 100];
_vehicle addAction ["Set to Rita", "(_this select 0) setVariable ['GVAR(GPWSmode)', 'rita', true]", nil, 1.01123, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] != 'rita')", 100];
_vehicle addAction ["Test GPWS (B747)", "[_this select 0] spawn FUNC(b747GPWStest)", nil, 1.01131, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] isEqualTo 'b747') && (_target getVariable ['GVAR(GPWStestReady)', true])", 100];
_vehicle addAction ["Test GPWS (Betty)", "[_this select 0] spawn FUNC(f16GPWStest)", nil, 1.01132, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] isEqualTo 'f16') && (_target getVariable ['GVAR(GPWStestReady)', true])", 100];
_vehicle addAction ["Test GPWS (Rita)", "[_this select 0] spawn FUNC(ritaGPWStest)", nil, 1.01133, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] isEqualTo 'rita') && (_target getVariable ['GVAR(GPWStestReady)', true])", 100];
_vehicle addAction ["Stop GPWS Test", "(_this select 0) setVariable ['GVAR(GPWStestStop)', true, true]", nil, 1.01134, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSmodeLocal)', 'off'] != 'off') && !(_target getVariable ['GVAR(GPWStestReady)', true]) && !(_target getVariable ['GVAR(GPWStestStop)', false])", 100];
_vehicle addAction ["Lower Volume", "(_this select 0) setVariable ['GVAR(GPWSvolumeLow)', true, true]", nil, 1.01141, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && !(_target getVariable ['GVAR(GPWSvolumeLow)', false])", 100];
_vehicle addAction ["Increase Volume", "(_this select 0) setVariable ['GVAR(GPWSvolumeLow)', false, true]", nil, 1.01142, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(GPWSenabled)', false]) && (_target getVariable ['GVAR(GPWSvolumeLow)', false])", 100];
// _vehicle addAction ["TCAS TA/RA", "(_this select 0) setVariable ['GVAR(tcasMode)', 2, true]", nil, 1.0121, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(tcasMode)', 0] != 2)", 100];
// _vehicle addAction ["TCAS TA", "(_this select 0) setVariable ['GVAR(tcasMode)', 1, true]", nil, 1.0122, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(tcasMode)', 0] != 1)", 100];
// _vehicle addAction ["TCAS Stand By", "(_this select 0) setVariable ['GVAR(tcasMode)', 0, true]", nil, 1.0123, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(tcasMode)', 0] != 0)", 100];
_vehicle addAction ["TCAS Mode C", "(_this select 0) setVariable ['GVAR(transponderMode)', 2, true]", nil, 1.0131, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(transponderMode)', 0] != 2)", 100];
_vehicle addAction ["TCAS Stand By", "(_this select 0) setVariable ['GVAR(transponderMode)', 1, true]", nil, 1.0132, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(transponderMode)', 0] != 1)", 100];
_vehicle addAction ["TCAS Off", "(_this select 0) setVariable ['GVAR(transponderMode)', 0, true]", nil, 1.0133, false, true, "", "([nil, _target, 1] call EFUNC(main,isCrew)) && (_target getVariable ['GVAR(transponderMode)', 0] != 0)", 100];
_vehicle setVariable [QGVAR(hasAction), true, true];
